apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nodejs-app.fullname" . }}-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: {{ .Values.environment }}
  PORT: "{{ .Values.service.targetPort }}"
